on:
  label:
    types:
      - created

  push:
    branches:
      - main

  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

      lastname:
        description: 'A last name of the user from the caller workflow'
        default: 'doe'
        required: false
        type: string

  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
      - main
jobs: 
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: |
          echo  ${{ inputs.username }}
      
  print-lastname:
    runs-on: ubuntu-latest

    steps:
      - name: Print the last name to STDOUT
        run: |
          echo ${{ inputs.lastname }}
    