on:
  label:
    types:
      - created
  push:
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building"
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: echo "publishing"